librosonline/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('vistaprevia/', include('vistaprevia.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

vistaprevia/urls.py
from django.urls import path
from vistaprevia import views


urlpatterns = [
    path('', views.index, name='index'),
	path('cargar/', views.cargar_imagen, name='cargar'),
	path('<int:producto_id>/ver/', views.ver_imagen, name='ver'),
	path('verimagenes', views.ver_imagenes, name='verimagenes'),
]

vistaprevia/models.py
from django.db import models

class Producto(models.Model):
	producto = models.CharField(max_length=200)
	fecha_publicacion = models.DateTimeField('Fecha de publicación')
	ruta_imagen = models.FileField(upload_to='fotos/%Y/%m/%d',default='defecto/defecto.png', blank=True, null=True)
 
	def __str__(self):
 
		return ('<%s => %s: %s, %s>' % (self.__class__.__name__, self.producto,self.fecha_publicacion, self.ruta_imagen)) 

vistaprevia/forms.py
from django.forms import ModelForm
from .models import Producto

class CargarForm(ModelForm):
 
	class Meta:
		model = Producto
		fields = ['producto', 'fecha_publicacion', 'ruta_imagen']
		error_messages = {
			'producto': {
			'required': ("Se debe agregar un nombre de producto"),
			},
			'fecha_publicacion': {
			'required': ("Se debe agregar la fecha de publicación en el formato adecuado"),
			},
		}
	def __init__(self, *args, **kwargs):
		super(CargarForm, self).__init__(*args, **kwargs)

vistaprevia/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.shortcuts import redirect
from vistaprevia.models import Producto
from vistaprevia.forms import CargarForm
from django.http import Http404
from django.shortcuts import render_to_response


def index(request):
    contenido = { 'nombre_sitio': 'LibrosOnline' }
    para_minorista = { 'tipo_usuario' : 'minorista' , 'incremento' : '25'}
    para_mayorista = { 'tipo_usuario' : 'mayorista' , 'incremento' : '10'}
    return render(request,
	'vistaprevia/index.html', {'contenido':contenido,
	'para_minorista':para_minorista,
	'para_mayorista':para_mayorista})




def cargar_imagen(request):
	if request.method == 'POST':
		form = CargarForm(request.POST, request.FILES)
		if form.is_valid():
			producto = form.cleaned_data['producto']
			fecha_publicacion = form.cleaned_data['fecha_publicacion']
			ruta_imagen = form.cleaned_data['ruta_imagen']
			newdoc = Producto(producto = producto, fecha_publicacion = fecha_publicacion,ruta_imagen = ruta_imagen)
			newdoc.save()
			#return redirect("index")
			return redirect("verimagenes")
	else:
		form = CargarForm()
	return render(request, 'vistaprevia/formulario.html', {'form': form})

def ver_imagen(request, producto_id):
	try:
		producto = Producto.objects.get(pk=producto_id)
	except Producto.DoesNotExist:
		raise Http404
	return render_to_response('vistaprevia/verimagen.html', {'producto': producto,'error_message': "No has seleccionado un producto.",},content_type=RequestContext(request))


def ver_imagenes(request):
	try:
		productos = Producto.objects.all()
	except Producto.DoesNotExist:
		raise Http404
	return render_to_response('vistaprevia/verimagenes.html', {'productos': productos,'error_message': "No has seleccionado un producto.",},content_type=RequestContext(request))

vistaprevia/templates/vistaprevia/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>{% block title %}{% if page_title %}{{ page_title }} - {% endif %}{{ site_name }}{% endblock %}</title>
    <meta name="keywords" content="{{ palabras_claves }}" />
    <meta name="description" content="{{ descripcion }}" />
	<link rel="stylesheet" type="text/css" href="{% static 'vistaprevia/css/bootstrap.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'vistaprevia/css/jquery-ui.css' %}" />	
	<link rel="stylesheet" type="text/css" href="{% static 'vistaprevia/css/style.css' %}" />
	<!-- <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" /> -->
	
  </head>
  <body>
    {% block contenedor %}{% endblock %}
  </body>
</html>

vistaprevia/templates/vistaprevia/formulario.html
{% extends "vistaprevia/plantilla.html" %}
{% load static %}
{% load i18n %}
{% block content %}
	 <div class="container">
		<!-- <div class="jumbotron">  -->
		<h1>Página de contacto.</h1>
		<!-- </div> -->
	 </div>
	 <main class="container-fluid">
		<div id="formulario_contacto" class="row">
			<div class="col-xs-offset-1 col-xs-10 col-sm-offset-1 col-sm-10col-md-offset-2 col-md-8">
				<h2>Contacto</h2>
				<hr/>
				<form class="col-xs-12 action="{% url 'cargar' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
					{{ form.as_p }}
					<input type="submit" value="Submit">
				</form>
			</div>
		</div>
	 </main>
{% endblock %}
{% block scripts %}
	 <script src="{% static 'vistaprevia/js/jquery-ui.js' %}"></script>
	 <script>
	 $( "#id_fecha_publicacion" ).datepicker({
	 inline: true
	 });
	 </script>
{% endblock %}

vistaprevia/templates/vistaprevia/index.html
{% extends "vistaprevia/plantilla.html" %}
{% load static %}
{% load i18n %}
{% block content %}
		<h2>Bienvenido a : {{contenido.nombre_sitio}}.!</h2>
	
		{% if para_minorista.incremento == '10' %}
			<h2>El incremento para minoristas es del: {{para_minorista.incremento}}%.!</h2> 
		{% elif para_minorista.incremento == '20' %}
			<h2>El incremento para minoristas es del: {{para_minorista.incremento}}%.!</h2> 	
		{% else %}
			<h2>El incremento para minoristas es del: {{para_minorista.incremento}}%.!</h2> 	
		{% endif%}
{% endblock %}

vistaprevia/templates/vistaprevia/plantilla.html
{% extends "vistaprevia/base.html" %}
{% block contenedor %}
      <header class="container-fluid">
		<div class="row">
			<div style="background-color:#9999ff; color:#000;text-align:center; height:70px;" class="col-xs-12">
				<h1>Paisajes de la Argentina</h1> 
			</div>
		</div>
      </header>
      <div class="container">
		<div class="row">
			<div style="background-color:#ccccff;" class="col-xs-12 col-sm-12 col-md-12">
				{% block content %}{% endblock %}
			</div>
		</div>
      </div>
      <footer class="container-fluid">
		<div class="row">
			<div style="background-color:#99ff99; color:#003300;text-align:center; height:40px;" class="col-xs-12">
				<h4>Copyright 2019 - Desarrollos web s.a.</h4>
				<h5>Conociendo nuestro pais</h5>
			</div>
		</div>
      </footer>
{% endblock %}

vistaprevia/templates/vistaprevia/verimagen.html
{% extends "vistaprevia/plantilla.html" %}
{% load static %}
{% load i18n %}
{% block content %}
 <div class="container">
	<div class="jumbotron">
		<h2>Ver Cada Imagen</h2>
	</div>
 </div>
 <main class="container">
	<div class="row" >
		<section class="col-12" style=" padding:30px; 30px; 230px; 30px;">
			<h4> El id de la imagen es: {{ producto.id }}</h4>
			<h2> Titulo: {{ producto.producto }}</h2>
			<h3> Fecha: {{ producto.fecha_publicacion }}</h3>
			{% load staticfiles %}
				<img src="/media/{{producto.ruta_imagen}}" alt="My image" width="50%"/>
				<a href="{% url 'verimagenes' %}">Volver a todas las imagenes</a>
		</section>
	</div>
 </main>
{% endblock %}

vistaprevia/templates/vistaprevia/verimagenes.html
{% extends "vistaprevia/plantilla.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<div class="container">
	<div class="jumbotron">
		<h2>Ver Todas las Imagenes</h2>
	</div>
</div>
<main class="container">
	<div class="row" >
		<section class="col-12" style=" padding:30px; 30px; 230px; 30px;">
			{% for productos in productos %}
				<a href="{% url 'ver' productos.id %}">
					<img src="/media/{{productos.ruta_imagen}}" alt="My image" width="20%"/>
				</a>
			{% endfor %}
		</section>
	</div>
 </main>
{% endblock %}